### ISSUE TITLE
Wrong shape in Code Cell 1 of Notebook "Part 3 - Training neural networks" (excercise as well as solution)?

### ISSUE THREAD

**Issue by DecisioNaut** [udacity/DSND_Term1#14]
To me it seems as if there was an error in Notebook(s) "Part 3 - Training neural networks":
When executing  Code-Cell 1 with `transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)), ])` Code-Cell 2 produces an error stating `RuntimeError: output with shape [1, 28, 28] doesn't match the broadcast shape [3, 28, 28]`.

In my opinion it should be `transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,), (0.5,)), ])` (like in Part 2).

Thanks for checking and amending if necessary!

**Comment by DecisioNaut** [comment]
Actually, the same goes with Notebook(s) "Part 4 - Fashion MNIST"... Also here, thanks for checking and amending if necessary!

**Comment by benvenutto** [comment]
@QuantificAid which version of PyTorch are you running, as there seem to be breaking changes to broadcast in 1.3? You can run:

**Comment by SudKul** [comment]
Thank you, @QuantificAid 
We have rectified the issue on this [PR#12 ](https://github.com/udacity/DSND_Term1/pull/12).
