### ISSUE TITLE
Projects in repo are a part of current 'Intro to Machine Learning' nanodegree not 'Data Science' nanodegree.

### ISSUE THREAD

**Issue by justinhoughton** [udacity/DSND_Term1#17]
Projects in this repo do not refer to _current_ [Data Science Nanodegree](https://www.udacity.com/course/data-scientist-nanodegree--nd025) but refer to the projects in the _current_ [Intro To Machine Learning Nanodegree](https://www.udacity.com/course/intro-to-machine-learning-nanodegree--nd229)

This caused a little bit of confusion when first cloning the repo and starting on projects within the Intro To Machine Learning Nanodegree. Both the README.md files and the notebook files are out of date.

**Comment by justinhoughton** [comment]
Would be happy to throw a PR up to change the ipython notebook text + README.

The PR wouldn't contain changing the repo name, since the current link on the lesson takes you here (via the DSND_Term1 repo url).

Let me know! (Not sure if Udacity let's others contribute)

**Comment by SudKul** [comment]
Hi @justinhoughton 
Thanks for bringing this to our notice. We have changed the ND name in the README file. 
Yes, we will be happy to review your PRs to update the notebook files.
