### ISSUE TITLE
Importing train test split module outdated (py1charityml jupyter notebook)

### ISSUE THREAD

**Issue by Jannis12324** [udacity/DSND_Term1#20]
Importing the module with 
`from sklearn.cross_validation import train_test_split`
does not work anymore.
`from sklearn.model_selection import train_test_split`
works.

**Comment by i3abghany** [comment]
I encountered the same issue and It's not yet solved.

**Comment by SudKul** [comment]
Thanks, @Jannis12324 
We have updated all occurrences of the deprecated `from sklearn.cross_validation import train_test_split` in [this](https://github.com/udacity/DSND_Term1/commit/226c26478c64a34611c5117abb51e7bb72b95888) commit.
