### ISSUE TITLE
Clone

### ISSUE THREAD

**Issue by digs1998** [udacity/DSND_Term1#22]
I can't see any cloning option

**Comment by SudKul** [comment]
Hi @digs1998 
Go to the repository home: https://github.com/udacity/DSND_Term1 to find the cloning options. See a snapshot below:
<img width="1168" alt="Screenshot 2020-11-27 at 4 46 41 PM" src="https://user-images.githubusercontent.com/48475411/100443735-41c9b100-30d0-11eb-8639-4c5022ec4386.png">
